"""create calls and analyses tables

Revision ID: 7890a1ac2ef2
Revises: 
Create Date: 2026-04-29 19:16:18.979136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7890a1ac2ef2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('rep_name', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_title', sa.String(length=100), nullable=True),
    sa.Column('deal_stage', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('deal_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('competitor_mentioned', sa.String(length=150), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('areas_for_improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objections_raised', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_call_id'), 'analyses', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_call_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('calls')
    # ### end Alembic commands ###
